// Code generated by mockery v2.33.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	dao "github.com/a-novel/authorizations-service/pkg/dao"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// UserAuthorizationsRepository is an autogenerated mock type for the UserAuthorizationsRepository type
type UserAuthorizationsRepository struct {
	mock.Mock
}

type UserAuthorizationsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserAuthorizationsRepository) EXPECT() *UserAuthorizationsRepository_Expecter {
	return &UserAuthorizationsRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, userID
func (_m *UserAuthorizationsRepository) Get(ctx context.Context, userID uuid.UUID) (*dao.UserAuthorizations, error) {
	ret := _m.Called(ctx, userID)

	var r0 *dao.UserAuthorizations
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dao.UserAuthorizations, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dao.UserAuthorizations); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.UserAuthorizations)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserAuthorizationsRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UserAuthorizationsRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *UserAuthorizationsRepository_Expecter) Get(ctx interface{}, userID interface{}) *UserAuthorizationsRepository_Get_Call {
	return &UserAuthorizationsRepository_Get_Call{Call: _e.mock.On("Get", ctx, userID)}
}

func (_c *UserAuthorizationsRepository_Get_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *UserAuthorizationsRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserAuthorizationsRepository_Get_Call) Return(_a0 *dao.UserAuthorizations, _a1 error) *UserAuthorizationsRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserAuthorizationsRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*dao.UserAuthorizations, error)) *UserAuthorizationsRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, userID, core, fields, now
func (_m *UserAuthorizationsRepository) Set(ctx context.Context, userID uuid.UUID, core dao.UserAuthorizationsCore, fields dao.AuthorizationFields, now time.Time) (*dao.UserAuthorizations, error) {
	ret := _m.Called(ctx, userID, core, fields, now)

	var r0 *dao.UserAuthorizations
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dao.UserAuthorizationsCore, dao.AuthorizationFields, time.Time) (*dao.UserAuthorizations, error)); ok {
		return rf(ctx, userID, core, fields, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dao.UserAuthorizationsCore, dao.AuthorizationFields, time.Time) *dao.UserAuthorizations); ok {
		r0 = rf(ctx, userID, core, fields, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.UserAuthorizations)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dao.UserAuthorizationsCore, dao.AuthorizationFields, time.Time) error); ok {
		r1 = rf(ctx, userID, core, fields, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserAuthorizationsRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type UserAuthorizationsRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - core dao.UserAuthorizationsCore
//   - fields dao.AuthorizationFields
//   - now time.Time
func (_e *UserAuthorizationsRepository_Expecter) Set(ctx interface{}, userID interface{}, core interface{}, fields interface{}, now interface{}) *UserAuthorizationsRepository_Set_Call {
	return &UserAuthorizationsRepository_Set_Call{Call: _e.mock.On("Set", ctx, userID, core, fields, now)}
}

func (_c *UserAuthorizationsRepository_Set_Call) Run(run func(ctx context.Context, userID uuid.UUID, core dao.UserAuthorizationsCore, fields dao.AuthorizationFields, now time.Time)) *UserAuthorizationsRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(dao.UserAuthorizationsCore), args[3].(dao.AuthorizationFields), args[4].(time.Time))
	})
	return _c
}

func (_c *UserAuthorizationsRepository_Set_Call) Return(_a0 *dao.UserAuthorizations, _a1 error) *UserAuthorizationsRepository_Set_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserAuthorizationsRepository_Set_Call) RunAndReturn(run func(context.Context, uuid.UUID, dao.UserAuthorizationsCore, dao.AuthorizationFields, time.Time) (*dao.UserAuthorizations, error)) *UserAuthorizationsRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserAuthorizationsRepository creates a new instance of UserAuthorizationsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserAuthorizationsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserAuthorizationsRepository {
	mock := &UserAuthorizationsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
